#!/bin/bash
source environment.sh && \
docker build --build-arg CONTAINER_CENTOS_VERSION=$CONTAINER_CENTOS_VERSION \
             --build-arg CONTAINER_SLURM_VERSION=$CONTAINER_SLURM_VERSION \
             --build-arg CONTAINER_PYTHON_VERSION=$CONTAINER_PYTHON_VERSION \
             --build-arg CONTAINER_USERS=$CONTAINER_USERS \
			 -f $DOCKERFILE_PATH \
			 -t $IMAGE_NAME "$@" .
exit
